begin;

alter table public.workout_logs
  alter column rpe drop not null,
  alter column pain drop not null,
  add column source text not null default 'manual',
  add column strava_activity_id text,
  add column activity_type text not null default 'easy',
  add column provider_activity_type text,
  add column feeling integer,
  add column location_name text,
  add column location_city text,
  add column route_name text,
  add column latitude numeric(9, 6),
  add column longitude numeric(9, 6),
  add column elevation_gain numeric(9, 2),
  add column calories numeric(9, 2),
  add column weather jsonb,
  add constraint workout_logs_source_allowed
    check (source in ('manual', 'strava')),
  add constraint workout_logs_activity_type_allowed
    check (activity_type in ('easy', 'long_run', 'tempo', 'interval', 'race', 'recovery')),
  add constraint workout_logs_feeling_range
    check (feeling is null or feeling between 1 and 10),
  add constraint workout_logs_latitude_range
    check (latitude is null or latitude between -90 and 90),
  add constraint workout_logs_longitude_range
    check (longitude is null or longitude between -180 and 180),
  add constraint workout_logs_elevation_nonnegative
    check (elevation_gain is null or elevation_gain >= 0),
  add constraint workout_logs_calories_nonnegative
    check (calories is null or calories >= 0),
  add constraint workout_logs_strava_identity
    check (
      (source = 'strava' and strava_activity_id is not null)
      or (source = 'manual' and strava_activity_id is null)
    );

create unique index workout_logs_user_strava_activity_unique_idx
  on public.workout_logs (user_id, strava_activity_id)
  where strava_activity_id is not null;

create table public.connected_integrations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null,
  provider_user_id text not null,
  access_token text not null,
  refresh_token text not null,
  expires_at timestamptz not null,
  scopes text[] not null default '{}'::text[],
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint connected_integrations_owner_provider_unique unique (user_id, provider),
  constraint connected_integrations_provider_allowed check (provider in ('strava')),
  constraint connected_integrations_provider_user_not_empty
    check (char_length(trim(provider_user_id)) > 0),
  constraint connected_integrations_access_token_not_empty
    check (char_length(access_token) > 0),
  constraint connected_integrations_refresh_token_not_empty
    check (char_length(refresh_token) > 0)
);

comment on column public.connected_integrations.access_token is
  'AES-256-GCM ciphertext generated by the server; never a plaintext token.';
comment on column public.connected_integrations.refresh_token is
  'AES-256-GCM ciphertext generated by the server; never a plaintext token.';

create table public.run_splits (
  id uuid primary key default gen_random_uuid(),
  workout_id uuid not null references public.workout_logs(id) on delete cascade,
  kilometer integer not null,
  pace_seconds integer not null,
  distance_meters numeric(8, 2) not null default 1000,
  elevation_difference numeric(8, 2),
  created_at timestamptz not null default now(),
  constraint run_splits_workout_kilometer_unique unique (workout_id, kilometer),
  constraint run_splits_kilometer_positive check (kilometer > 0),
  constraint run_splits_pace_positive check (pace_seconds > 0),
  constraint run_splits_distance_positive check (distance_meters > 0)
);

create table public.activity_routes (
  id uuid primary key default gen_random_uuid(),
  workout_id uuid not null unique references public.workout_logs(id) on delete cascade,
  polyline text not null,
  distance_stream jsonb not null default '[]'::jsonb,
  elevation_stream jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  constraint activity_routes_polyline_not_empty check (char_length(trim(polyline)) > 0),
  constraint activity_routes_distance_stream_array check (jsonb_typeof(distance_stream) = 'array'),
  constraint activity_routes_elevation_stream_array check (jsonb_typeof(elevation_stream) = 'array')
);

create index connected_integrations_user_provider_idx
  on public.connected_integrations (user_id, provider);
create index run_splits_workout_kilometer_idx
  on public.run_splits (workout_id, kilometer);

create trigger connected_integrations_set_updated_at
before update on public.connected_integrations
for each row execute function public.set_updated_at();

alter table public.connected_integrations enable row level security;
alter table public.run_splits enable row level security;
alter table public.activity_routes enable row level security;

create policy "connected_integrations_select_own"
on public.connected_integrations for select to authenticated
using ((select auth.uid()) = user_id);

create policy "connected_integrations_insert_own"
on public.connected_integrations for insert to authenticated
with check ((select auth.uid()) = user_id);

create policy "connected_integrations_update_own"
on public.connected_integrations for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "connected_integrations_delete_own"
on public.connected_integrations for delete to authenticated
using ((select auth.uid()) = user_id);

create policy "run_splits_select_own"
on public.run_splits for select to authenticated
using (
  exists (
    select 1 from public.workout_logs
    where workout_logs.id = run_splits.workout_id
      and workout_logs.user_id = (select auth.uid())
  )
);

create policy "run_splits_insert_own"
on public.run_splits for insert to authenticated
with check (
  exists (
    select 1 from public.workout_logs
    where workout_logs.id = run_splits.workout_id
      and workout_logs.user_id = (select auth.uid())
  )
);

create policy "run_splits_update_own"
on public.run_splits for update to authenticated
using (
  exists (
    select 1 from public.workout_logs
    where workout_logs.id = run_splits.workout_id
      and workout_logs.user_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1 from public.workout_logs
    where workout_logs.id = run_splits.workout_id
      and workout_logs.user_id = (select auth.uid())
  )
);

create policy "run_splits_delete_own"
on public.run_splits for delete to authenticated
using (
  exists (
    select 1 from public.workout_logs
    where workout_logs.id = run_splits.workout_id
      and workout_logs.user_id = (select auth.uid())
  )
);

create policy "activity_routes_select_own"
on public.activity_routes for select to authenticated
using (
  exists (
    select 1 from public.workout_logs
    where workout_logs.id = activity_routes.workout_id
      and workout_logs.user_id = (select auth.uid())
  )
);

create policy "activity_routes_insert_own"
on public.activity_routes for insert to authenticated
with check (
  exists (
    select 1 from public.workout_logs
    where workout_logs.id = activity_routes.workout_id
      and workout_logs.user_id = (select auth.uid())
  )
);

create policy "activity_routes_update_own"
on public.activity_routes for update to authenticated
using (
  exists (
    select 1 from public.workout_logs
    where workout_logs.id = activity_routes.workout_id
      and workout_logs.user_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1 from public.workout_logs
    where workout_logs.id = activity_routes.workout_id
      and workout_logs.user_id = (select auth.uid())
  )
);

create policy "activity_routes_delete_own"
on public.activity_routes for delete to authenticated
using (
  exists (
    select 1 from public.workout_logs
    where workout_logs.id = activity_routes.workout_id
      and workout_logs.user_id = (select auth.uid())
  )
);

revoke all on public.connected_integrations from anon;
revoke all on public.run_splits from anon;
revoke all on public.activity_routes from anon;

grant select, insert, update, delete on public.connected_integrations to authenticated;
grant select, insert, update, delete on public.run_splits to authenticated;
grant select, insert, update, delete on public.activity_routes to authenticated;

commit;
